"""
Postgres async wrapper. Persistencia server-side de usuarios, diagnosticos y
sesiones de practica.

Driver: psycopg 3.x async + AsyncConnectionPool. Connection string en
`settings.database_url` (libpq estandar, sin prefijo "+psycopg").

# Schema
Definido inline en BASE_SCHEMA. Reglas de portabilidad (post-piloto cuando
migremos a otro backend o agreguemos read replicas):
- BIGINT GENERATED BY DEFAULT AS IDENTITY        (no SERIAL ni AUTOINCREMENT)
- TIMESTAMPTZ para timestamps server-side
- TEXT para strings y JSON serializado (migrar a JSONB con ALTER TABLE
  ... USING ::jsonb cuando convenga indexarlo)
- BOOLEAN para flags (no INTEGER 0/1)
- FKs explicitas — Postgres las enforza por default, no hay PRAGMA

# Migraciones
Tabla `schema_version` mas funcion `apply_migrations()` aplican statements
idempotentes en orden. Sin Alembic para no traer la dep en piloto; cuando
crezca el numero de migraciones lo introducimos con baseline.
"""

import logging
from contextlib import asynccontextmanager
from typing import AsyncIterator

from psycopg import AsyncConnection
from psycopg.errors import DuplicateColumn, DuplicateObject, DuplicateTable
from psycopg.rows import dict_row
from psycopg_pool import AsyncConnectionPool

from app.config import settings

logger = logging.getLogger("menteviva")


# ============================================================
# Schema base — version 0 (idempotente)
# ============================================================

BASE_SCHEMA = """
CREATE TABLE IF NOT EXISTS schema_version (
    version    INTEGER PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
    -- user_id = Firebase UID. Mantener TEXT permite tambien UUIDs legacy.
    user_id           TEXT PRIMARY KEY,
    nombre            TEXT NOT NULL,
    email             TEXT,
    rol_objetivo      TEXT NOT NULL,
    industria         TEXT NOT NULL,
    experience_level  TEXT NOT NULL,
    created_at        TEXT NOT NULL,
    updated_at        TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS diagnostics (
    diagnostic_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            TEXT NOT NULL REFERENCES users(user_id),
    completed_at       TEXT NOT NULL,
    -- TEXT con JSON serializado. Migrar a JSONB cuando necesitemos GIN index.
    diagnostico_json   TEXT NOT NULL,
    conversation_json  TEXT NOT NULL,
    is_demo            BOOLEAN NOT NULL DEFAULT FALSE,
    created_at         TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_diagnostics_user ON diagnostics(user_id);
CREATE INDEX IF NOT EXISTS idx_diagnostics_created ON diagnostics(created_at);

CREATE TABLE IF NOT EXISTS practice_sessions (
    session_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            TEXT NOT NULL REFERENCES users(user_id),
    avatar_id          TEXT NOT NULL,
    level              TEXT,
    started_at         TEXT NOT NULL,
    ended_at           TEXT NOT NULL,
    duration_seconds   INTEGER,
    total_exchanges    INTEGER,
    overall_score      INTEGER,
    analysis_json      TEXT,
    conversation_json  TEXT,
    created_at         TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sessions_user ON practice_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_created ON practice_sessions(created_at);
"""


# ============================================================
# Migraciones incrementales
# ============================================================
# Cada entrada: (version, descripcion, lista_de_statements).
# Las migraciones se aplican en orden y solo si version > MAX(schema_version).
# Postgres soporta IF NOT EXISTS en ADD COLUMN — los statements son nativamente
# idempotentes. Mantenemos el try/except por seguridad si alguien corrio una
# migracion a mano sin actualizar schema_version.

MIGRATIONS: list[tuple[int, str, list[str]]] = [
    (
        1,
        "auth fields: password_hash, last_login, email_verified, UNIQUE email",
        [
            "ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash TEXT",
            "ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TEXT",
            "ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE",
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(email)",
        ],
    ),
    (
        2,
        "firebase: provider + uid metadata para usuarios autenticados via Firebase",
        [
            "ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_provider TEXT",
            "ALTER TABLE users ADD COLUMN IF NOT EXISTS firebase_uid TEXT",
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_users_firebase_uid ON users(firebase_uid)",
        ],
    ),
]


# ============================================================
# Pool de conexiones (lazy, una sola instancia por proceso)
# ============================================================

_pool: AsyncConnectionPool | None = None


def _build_pool() -> AsyncConnectionPool:
    """Crea el pool. No abre conexiones todavia (open=False permite warm-up
    durante startup_db)."""
    return AsyncConnectionPool(
        conninfo=settings.database_url,
        min_size=settings.db_pool_min_size,
        max_size=settings.db_pool_max_size,
        kwargs={"row_factory": dict_row},
        open=False,
    )


async def _get_pool() -> AsyncConnectionPool:
    global _pool
    if _pool is None:
        _pool = _build_pool()
        await _pool.open(wait=True, timeout=10.0)
        logger.info(
            f"[DB] pool abierto (min={settings.db_pool_min_size}, "
            f"max={settings.db_pool_max_size})"
        )
    return _pool


async def close_pool() -> None:
    global _pool
    if _pool is not None:
        await _pool.close()
        _pool = None
        logger.info("[DB] pool cerrado")


# ============================================================
# Migrator
# ============================================================

async def _current_version(conn: AsyncConnection) -> int:
    async with conn.cursor() as cur:
        await cur.execute("SELECT MAX(version) AS v FROM schema_version")
        row = await cur.fetchone()
        return (row["v"] if row and row["v"] is not None else 0)


async def _apply_migration(
    conn: AsyncConnection, version: int, description: str, statements: list[str]
) -> None:
    """Aplica una migracion. Tolera duplicados (columna/indice ya existe) cuando
    alguien corrio la migracion a mano antes de registrarla en schema_version."""
    async with conn.cursor() as cur:
        for stmt in statements:
            try:
                await cur.execute(stmt)  # type: ignore[arg-type]
            except (DuplicateColumn, DuplicateObject, DuplicateTable) as e:
                logger.info(f"[DB][migrate v{version}] skip (ya existe): {stmt[:60]} — {e}")
                # psycopg deja la txn en error state; rollback y seguimos.
                await conn.rollback()
                continue
        await cur.execute(
            "INSERT INTO schema_version (version) VALUES (%s)",
            (version,),
        )
    await conn.commit()
    logger.info(f"[DB][migrate v{version}] OK — {description}")


async def init_db() -> None:
    """Abre el pool, aplica el schema base y todas las migraciones pendientes."""
    pool = await _get_pool()
    async with pool.connection() as conn:
        async with conn.cursor() as cur:
            # executemany no aplica para DDL; ejecutamos el script completo de
            # una. psycopg permite multi-statement en una sola execute().
            await cur.execute(BASE_SCHEMA)  # type: ignore[arg-type]
        await conn.commit()

        current = await _current_version(conn)
        pending = [m for m in MIGRATIONS if m[0] > current]
        if pending:
            logger.info(
                f"[DB] schema_version actual={current}, "
                f"aplicando {len(pending)} migraciones..."
            )
            for version, desc, stmts in pending:
                await _apply_migration(conn, version, desc, stmts)
        else:
            logger.info(f"[DB] schema al dia (version {current})")
    logger.info(f"[DB] Postgres listo en {_obscure_url(settings.database_url)}")


def _obscure_url(url: str) -> str:
    """Quita credenciales del DSN para loguear sin filtrar secrets."""
    # postgresql://user:pwd@host:port/db -> postgresql://user:***@host:port/db
    try:
        scheme, rest = url.split("://", 1)
        if "@" not in rest:
            return url
        creds, host = rest.rsplit("@", 1)
        if ":" in creds:
            user, _pwd = creds.split(":", 1)
            return f"{scheme}://{user}:***@{host}"
        return url
    except Exception:
        return "<unparseable>"


# ============================================================
# Connection helper para los repos
# ============================================================

@asynccontextmanager
async def get_db() -> AsyncIterator[AsyncConnection]:
    """Context manager que toma una conexion del pool. Las queries usan `%s`
    como placeholder (DB-API estandar de psycopg). Cada `async with` hace
    commit/rollback automatico al salir del bloque."""
    pool = await _get_pool()
    async with pool.connection() as conn:
        yield conn
